### PR TITLE
Fixes #43 Docker image

### LINKED ISSUE #43: docker image

### PR DESCRIPTION
**Pull request by pierreavizou**
This PR contains a "docker" folder with the necessary files and instructions to build and run a docker image of Serposcope. 
I needed one but could not find any, so I made it and now is the time to share with everyone. Hope it helps.

### CODE REVIEW

**Comment by serphacker** [comment]
`java -jar /usr/share/serposcope/serposcope.jar >$LOGDIR/startup.log` is not the right way to start serposcope, there is an init.d script. You should use : 

`service serposcope start`

**Comment by pierreavizou** [comment]
Yep I tried this actually, but there is a problem with this approach. Launching as a service causes the container to stop immediately, because a service is not a foreground process. In order not to stop, docker needs to have a foreground process running in the container.

**Comment by serphacker** [comment]
ok I understand (I'm not a docker expert).

I think serposcope is already launched (it is automatically started after package setup). CMD is launching it a second time which is not the right way. Can you try this : 

`CMD tail -F /var/log/serposcope/startup.log`

it should maintains a "related" foreground process this way

**Comment by pierreavizou** [comment]
Ok I understand what you mean. 
Actually, the serposcope installation is done inside the Dockerfile, and this only "copies" the serposcope files into their right place, is does not launch the service. The reason is that image building is a static process, which means that the serposcope image is just a basic Ubuntu image with java 8 and Serposcope installed. 
When launching the container, serposcope is not run automatically. 
I have just checked to be sure, when replacing my CMD with 

``` CMD tail -F /var/log/serposcope/startup.log ``` 

and running a ``` ps aux``` inside the container,  we have no trace of a running Serposcope or Java process:

```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.1  0.0   4336   756 ?        Ss   15:02   0:00 /bin/sh -c tail -F /var/log/serposcope/startup.log /bin/sh -c
root         6  0.0  0.0   5956   720 ?        S    15:02   0:00 tail -F /var/log/serposcope/startup.log
root         7  1.0  0.1  21924  3412 ?        Ss   15:02   0:00 bash
root        11  0.0  0.1  19188  2388 ?        R+   15:02   0:00 ps aux
``` 
However, I have found a way to launch Serposcope in a clean way thanks to you suggestion. When replacing the CMD with:

```CMD service serposcope start && tail -F /var/log/serposcope/startup.log``` 

The container does not stop, a Serposcope is running. 
I have just pushed the related commit, let me know if this is ok for you :-)

**Comment by serphacker** [comment]
LGTM

I'll add small adjustement : using jre instead of jdk and copy of default configuration before install.

**Comment by pierreavizou** [comment]
Thanks for merging :) 
If you copy the default conf file *before* install, it will either: 
- Be overwritten by dpkg when installing the .deb
- dpkg will prompt the user to choose between keeping or overwriting. This will cause the image building process to crash, because docker does not support interactive prompts when building images. 

Regarding the use of the JRE, it is indeed a good idea, I did not pay attention to that. 
All you have to do is replace the first line by 

```FROM java:8-jre```

That will indeed produce a lighter image.

**Comment by serphacker** [comment]
Yep that's what I did 290491a944f65fff5ae2daac030d5ce01f674f7d

**Comment by pierreavizou** [comment]
You were faster than me :)

**Pull request merged**
