### PR TITLE
mod charts display

### PR DESCRIPTION
**Pull request by st-a-ch**

### CODE REVIEW

**Comment by serphacker** [comment]
Hi can you describe what this PR is doing, do you have screenshot ?

**Comment by st-a-ch** [comment]
http://serwer.hyzne.com/temp/serposcope/ SEO3.rar - need another modyfed files
my mod its more complicated - use admin/ user/etc 
if admin full acces in nice charts on index.php if user only project charts /view?id/

not finished yet index.php need request from database for line - actually random data set

unpack all file - log admin - admin or change pass for difrent project in .htpasswd

**Comment by loran750** [comment]
Hello St-a-ch, I'm wondering from January which point reached by your fork.
The screenshots are really interesting, but I've tried to test the forked files (from patch 2 to 7) and didn't succeded in making them work (some files are missing in the repos)
regards

**Comment by st-a-ch** [comment]
wiev my panel live clientside http://seo.hyzne.com/ user:wideofilmowanie
pass:p@ss im not using GitHub if you want to prepare rar from all files in
my modding system

2015-04-26 11:50 GMT+02:00 Laurent <notifications@github.com>:

**Pull request closed without merging**
